import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { saveAs } from 'file-saver';

interface ExportOptions {
  title?: string;
  author?: string;
}

// Parse markdown into structured sections
function parseMarkdown(markdown: string): { title: string; content: string }[] {
  const sections: { title: string; content: string }[] = [];
  const lines = markdown.split('\n');
  let currentSection: { title: string; content: string } | null = null;

  for (const line of lines) {
    if (line.startsWith('## ')) {
      if (currentSection) {
        sections.push(currentSection);
      }
      currentSection = { title: line.slice(3).trim(), content: '' };
    } else if (line.startsWith('# ')) {
      if (currentSection) {
        sections.push(currentSection);
      }
      currentSection = { title: line.slice(2).trim(), content: '' };
    } else if (currentSection) {
      currentSection.content += line + '\n';
    }
  }

  if (currentSection) {
    sections.push(currentSection);
  }

  return sections;
}

// Clean text for PDF (remove markdown formatting)
function cleanTextForPdf(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '$1') // Bold
    .replace(/\*(.*?)\*/g, '$1') // Italic
    .replace(/`(.*?)`/g, '$1') // Code
    .replace(/^\s*[-*]\s+/gm, '• ') // List items
    .replace(/^\s*\d+\.\s+/gm, (match) => match) // Numbered lists
    .trim();
}

export async function exportToPdf(markdown: string, options: ExportOptions = {}): Promise<void> {
  const { title = 'Document', author = 'DocRAG' } = options;
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPosition = margin;

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, yPosition);
  yPosition += 15;

  // Subtitle/Author
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by ${author} | ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 10;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Reset text color
  doc.setTextColor(0, 0, 0);

  const sections = parseMarkdown(markdown);

  for (const section of sections) {
    // Check if we need a new page
    if (yPosition > pageHeight - 40) {
      doc.addPage();
      yPosition = margin;
    }

    // Section title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, yPosition);
    yPosition += 10;

    // Section content
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    const cleanContent = cleanTextForPdf(section.content);
    const lines = doc.splitTextToSize(cleanContent, maxWidth);

    for (const line of lines) {
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 6;
    }

    yPosition += 8; // Space between sections
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Download
  doc.save(`${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
}

export async function exportToDocx(markdown: string, options: ExportOptions = {}): Promise<void> {
  const { title = 'Document', author = 'DocRAG' } = options;
  const sections = parseMarkdown(markdown);

  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 48,
        }),
      ],
      spacing: { after: 200 },
    })
  );

  // Subtitle
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by ${author} | ${new Date().toLocaleDateString()}`,
          size: 20,
          color: '808080',
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Sections
  for (const section of sections) {
    // Section heading
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      })
    );

    // Section content - split by paragraphs
    const paragraphs = section.content.split('\n\n').filter((p) => p.trim());

    for (const para of paragraphs) {
      const lines = para.split('\n').filter((l) => l.trim());

      for (const line of lines) {
        const trimmedLine = line.trim();

        // Handle bullet points
        if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: '• ' + trimmedLine.slice(2),
                  size: 22,
                }),
              ],
              indent: { left: 720 },
              spacing: { after: 100 },
            })
          );
        }
        // Handle numbered lists
        else if (/^\d+\.\s/.test(trimmedLine)) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: trimmedLine,
                  size: 22,
                }),
              ],
              indent: { left: 720 },
              spacing: { after: 100 },
            })
          );
        }
        // Regular paragraph
        else if (trimmedLine) {
          // Handle bold text
          const parts = trimmedLine.split(/(\*\*.*?\*\*)/);
          const textRuns: TextRun[] = parts.map((part) => {
            if (part.startsWith('**') && part.endsWith('**')) {
              return new TextRun({
                text: part.slice(2, -2),
                bold: true,
                size: 22,
              });
            }
            return new TextRun({
              text: part,
              size: 22,
            });
          });

          children.push(
            new Paragraph({
              children: textRuns,
              spacing: { after: 200 },
            })
          );
        }
      }
    }
  }

  const doc = new Document({
    creator: author,
    title: title,
    sections: [
      {
        children: children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${title.toLowerCase().replace(/\s+/g, '-')}.docx`);
}

export function exportToMarkdown(markdown: string, options: ExportOptions = {}): void {
  const { title = 'Document' } = options;
  const blob = new Blob([markdown], { type: 'text/markdown' });
  saveAs(blob, `${title.toLowerCase().replace(/\s+/g, '-')}.md`);
}
